from cogs.utils.classes.weapon.weapon import Weapon, Blood, Sgs, Dharoks, Guth

weapon_dict = {
    'dds': {'stats': {'max_hit': 33, 'min_hit': 0, 'spec_used': 25, 'times_hit': 2, 'type': 'melee',
                      'poison': True, 'freeze': False, 'base_heal': 0, },
            'weapon': Weapon,
            'standard_weapon': True,
            'description': '', },
    'whip': {'stats': {'max_hit': 40, 'min_hit': 0, 'spec_used': 0, 'times_hit': 1, 'type': 'melee',
                       'poison': False, 'freeze': False, 'base_heal': 0, },
             'weapon': Weapon,
             'standard_weapon': True,
             'description': '', },
    'eat': {'stats': {'max_hit': 0, 'min_hit': 0, 'spec_used': 0, 'times_hit': 1, 'type': 'item',
                      'poison': False, 'freeze': False, 'base_heal': 25, },
            'weapon': Weapon,
            'standard_weapon': True,
            'description': '', },
    'ice': {'stats': {'max_hit': 30, 'min_hit': 0, 'spec_used': 0, 'times_hit': 1, 'type': 'magic',
                      'poison': False, 'freeze': True, 'base_heal': 0, },
            'weapon': Weapon,
            'standard_weapon': False, 'cost': 100000,
            'description': 'Casts Ice Barrage on your enemy, freezing them and doing damage.', },
    'smoke': {'stats': {'max_hit': 30, 'min_hit': 0, 'spec_used': 0, 'times_hit': 1, 'type': 'magic',
                        'poison': True, 'freeze': False, 'base_heal': 0, },
              'weapon': Weapon,
              'standard_weapon': False, 'cost': 100000,
              'description': 'Casts Smoke Barrage on your enemy, Poisoning them and doing damage.', },
    'blood': {'stats': {'max_hit': 30, 'min_hit': 0, 'spec_used': 0, 'times_hit': 1, 'type': 'magic',
                        'poison': False, 'freeze': False, 'base_heal': 0, },
              'weapon': Blood,
              'standard_weapon': False, 'cost': 100000,
              'description': 'Casts Blood Barrage on your enemy, healing you for 75% of the damage.', },
    'kick': {'stats': {'max_hit': 10, 'min_hit': 0, 'spec_used': 0, 'times_hit': 1, 'type': 'melee',
                       'poison': False, 'freeze': False, 'base_heal': 0, },
             'weapon': Weapon,
             'standard_weapon': True, 'cost': 0,
             'description': 'Kick your opponent with all your might.', },
    'msb': {'stats': {'max_hit': 41, 'min_hit': 0, 'spec_used': 50, 'times_hit': 2, 'type': 'ranged',
                      'poison': False, 'freeze': False, 'base_heal': 0, },
            'weapon': Weapon,
            'standard_weapon': True, 'cost': 0,
            'description': 'Fire two rune arrows at once like its 2007.', },
    'acb': {'stats': {'max_hit': 45, 'min_hit': 0, 'spec_used': 0, 'times_hit': 1, 'type': 'ranged',
                      'poison': False, 'freeze': False, 'base_heal': 0, },
            'weapon': Weapon,
            'standard_weapon': True, 'cost': 0,
            'description': 'Shoot a bolt with the crossbow of your favorite god.', },
    'obby': {'stats': {'max_hit': 47, 'min_hit': 0, 'spec_used': 0, 'times_hit': 1, 'type': 'melee',
                       'poison': False, 'freeze': False, 'base_heal': 0, },
             'weapon': Weapon,
             'standard_weapon': True, 'cost': 0,
             'description': 'Hulk smash.', },
    # TODO: Make a class for this that makes it innacurate but capable of hitting higher than whip.
    'fire': {'stats': {'max_hit': 45, 'min_hit': 0, 'spec_used': 0, 'times_hit': 1, 'type': 'magic',
                       'poison': False, 'freeze': False, 'base_heal': 0, },
             'weapon': Weapon,
             'standard_weapon': True, 'cost': 0,
             'description': 'Casts your favorite fire-based magic spell towards your enemy.', },
    'gmaul': {'stats': {'max_hit': 33, 'min_hit': 0, 'spec_used': 100, 'times_hit': 3, 'type': 'melee',
                        'poison': False, 'freeze': False, 'base_heal': 0, },
              'weapon': Weapon,
              'standard_weapon': True, 'cost': 0,
              'description': 'Smack your foes with an over-sized stone hammer... 3 times in a row!', },
    'ballista': {'stats': {'max_hit': 65, 'min_hit': 0, 'spec_used': 50, 'times_hit': 1, 'type': 'ranged',
                           'poison': False, 'freeze': False, 'base_heal': 0, },
                 'weapon': Weapon,
                 'standard_weapon': True, 'cost': 0,
                 'description': 'Shoot a hand held ballista you had to kill a demented gorilla for.', },
    'dknife': {'stats': {'max_hit': 33, 'min_hit': 0, 'spec_used': 25, 'times_hit': 2, 'type': 'ranged',
                         'poison': False, 'freeze': False, 'base_heal': 0, },
               'weapon': Weapon,
               'standard_weapon': True, 'cost': 0,
               'description': 'Throw two knives at once like a crazy ex-girlfriend.', },
    'dclaws': {'stats': {'max_hit': 25, 'min_hit': 0, 'spec_used': 50, 'times_hit': 4, 'type': 'melee',
                         'poison': False, 'freeze': False, 'base_heal': 0, },
               'weapon': Weapon,
               'standard_weapon': False, 'cost': 1000000,
               'description': 'Embody the rage of a dragon and slash your enemies to shreds.', },
    'dbow': {'stats': {'max_hit': 47, 'min_hit': 8, 'spec_used': 50, 'times_hit': 2, 'type': 'ranged',
                       'poison': False, 'freeze': False, 'base_heal': 0, },
             'weapon': Weapon,
             'standard_weapon': False, 'cost': 100000,
             'description': 'You found this while rushing rushers.', },
    'ags': {'stats': {'max_hit': 79, 'min_hit': 9, 'spec_used': 75, 'times_hit': 1, 'type': 'melee',
                      'poison': False, 'freeze': False, 'base_heal': 0, },
            'weapon': Weapon,
            'standard_weapon': False, 'cost': 200000,
            'description': 'Armadyl had no use for this anyways.', },
    'sgs': {'stats': {'max_hit': 69, 'min_hit': 0, 'spec_used': 75, 'times_hit': 1, 'type': 'melee',
                      'poison': False, 'freeze': False, 'base_heal': 0, },
            'weapon': Sgs,
            'standard_weapon': False, 'cost': 200000,
            'description': 'Heal yourself with half the dmaage done by this sword', },
    'dh': {'stats': {'max_hit': 35, 'min_hit': 0, 'spec_used': 0, 'times_hit': 1, 'type': 'melee',
                     'poison': False, 'freeze': False, 'base_heal': 0, },
           'weapon': Dharoks,
           'standard_weapon': False, 'cost': 1000000,
           'description': 'Does more damage, the lower health you have.', },
    'guth': {'stats': {'max_hit': 35, 'min_hit': 0, 'spec_used': 0, 'times_hit': 1, 'type': 'melee',
                       'poison': False, 'freeze': False, 'base_heal': 0, },
             'weapon': Guth,
             'standard_weapon': False, 'cost': 250000,
             'description': 'Has a 1/3 chance to heal you for the amount of damage dealt', },
    'karils': {'stats': {'max_hit': 14, 'min_hit': 0, 'spec_used': 0, 'times_hit': 5, 'type': 'ranged',
                         'poison': False, 'freeze': False, 'base_heal': 0, },
               'weapon': Weapon,
               'standard_weapon': False, 'cost': 250000,
               'description': 'Shoots 5 low damage bolts', },
}
